name: Build and Test app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install packages/modules
      run: npm install
    # - name: Start app
    #   run: npm start    
    # - name: Install playwright for testing
    #   run: npx playwright install
    - name: Start tests
      run: npm run test:unit
    - name: Showcase student's name
      run: echo 'mdzhut200'

  execute-ui-test:
    needs: build-and-unit-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install Playwright browsers
      run:  npx playwright install
    # - name: Start the application
    #   run:  npm run start
    - name: Execute the UI tests
      run:  npm run test:ui

  deploy:
    needs: execute-ui-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}