name: Build and Test app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install packages/modules
      run: npm install
    # - name: Start app
    #   run: npm start    
    # - name: Install playwright for testing
    #   run: npx playwright install
    - name: Start tests
      run: npm start test:unit

